#!/usr/bin/env bash
#
# Collect missing sensitive operations input into a private Markdown document.
# Generated by the sensitive-ops skill.
#
# Keep the library above the "STAGES" marker unchanged. Author the missing
# outcomes below it with the exact placeholders already present in the document.

set -euo pipefail
umask 077

OPS_FILE="${SENSITIVE_OPS_FILE:-${HOME}/Documents/LLM/sensitive-ops.md}"
TOTAL_STAGES=0
_STAGE_INDEX=0
TRACKED_PLACEHOLDERS=()

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

say()  { printf '  %s\n' "$1"; }
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

defer() {
  printf '\n  %sProgress saved.%s Run this helper again when you are ready.\n\n' "$YELLOW" "$RESET"
  exit 2
}

trap defer INT TERM

ensure_ops_file() {
  mkdir -p "$(dirname "$OPS_FILE")"
  touch "$OPS_FILE"
  chmod 600 "$OPS_FILE"
}

placeholder_exists() {
  grep -Fq -- "$1" "$OPS_FILE"
}

track() {
  local placeholder
  for placeholder in "$@"; do TRACKED_PLACEHOLDERS+=("$placeholder"); done
}

count_pending() {
  local placeholder count=0
  for placeholder in "$@"; do
    if placeholder_exists "$placeholder"; then count=$((count + 1)); fi
  done
  printf '%s' "$count"
}

banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s remaining stage(s)%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  Durable results are saved to %s.\n' "$DIM" "$OPS_FILE"
  printf '  Enter :later or press Ctrl-C to stop; completed stages are retained.%s\n\n' "$RESET"
}

stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview      >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open     >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open         >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || defer
  [[ "$reply" == ":later" ]] && defer
  [[ "$reply" =~ ^[Yy]$ ]]
}

# Replace an exact placeholder without exposing its value to a child process.
# Placeholders must be unique and must not contain shell glob characters.
replace_placeholder() {
  local placeholder="$1" value="$2" tmp line prefix suffix found=0
  if [[ "$placeholder" == *'*'* || "$placeholder" == *'?'* || "$placeholder" == *'['* ]]; then
    warn "placeholder contains an unsupported glob character"
    return 1
  fi
  tmp=$(mktemp "${OPS_FILE}.tmp.XXXXXX")
  while IFS= read -r line || [[ -n "$line" ]]; do
    if [[ "$line" == *"$placeholder"* ]]; then
      prefix=${line%%"$placeholder"*}
      suffix=${line#*"$placeholder"}
      line="${prefix}${value}${suffix}"
      found=$((found + 1))
    fi
    printf '%s\n' "$line" >> "$tmp"
  done < "$OPS_FILE"
  if [[ "$found" -ne 1 ]]; then
    rm -f "$tmp"
    warn "expected one occurrence of placeholder, found $found"
    return 1
  fi
  chmod 600 "$tmp"
  mv "$tmp" "$OPS_FILE"
}

collect_value() {
  local placeholder="$1" prompt="$2" value=""
  placeholder_exists "$placeholder" || return 0
  printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  read -r value || defer
  [[ "$value" == ":later" ]] && defer
  if [[ -z "$value" ]]; then warn "a value is required, or enter :later"; return 2; fi
  replace_placeholder "$placeholder" "$value"
  printf '  %s✓ saved%s\n' "$GREEN" "$RESET"
}

collect_secret() {
  local placeholder="$1" prompt="$2" value=""
  placeholder_exists "$placeholder" || return 0
  printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  read -rs value || defer
  printf '\n'
  [[ "$value" == ":later" ]] && defer
  if [[ -z "$value" ]]; then warn "a value is required, or enter :later"; return 2; fi
  replace_placeholder "$placeholder" "$value"
  value=""
  printf '  %s✓ saved%s\n' "$GREEN" "$RESET"
}

complete_action() {
  local placeholder="$1" result="${2:-已完成}" today
  placeholder_exists "$placeholder" || return 0
  if ! confirm "Have you completed this action?"; then defer; fi
  today=$(date '+%Y-%m-%d')
  replace_placeholder "$placeholder" "${result}（${today}）"
  printf '  %s✓ recorded%s\n' "$GREEN" "$RESET"
}

finish() {
  local remaining
  remaining=$(count_pending "${TRACKED_PLACEHOLDERS[@]}")
  _clear
  if [[ "$remaining" -gt 0 ]]; then
    warn "$remaining tracked outcome(s) remain in $OPS_FILE"
    defer
  fi
  printf '\n%s%s  ✓ Sensitive operations input complete%s\n' "$BOLD" "$GREEN" "$RESET"
  note "The agent can now resume from $OPS_FILE."
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: replace this example with the current task's missing outcomes.
# Each placeholder must already exist exactly once in OPS_FILE.
# ──────────────────────────────────────────────────────────────────────────

ensure_ops_file

API_KEY_PLACEHOLDER='<待填写：Stripe test secret key>'
OAUTH_PLACEHOLDER='<待完成：批准 GitHub OAuth>'
track "$API_KEY_PLACEHOLDER" "$OAUTH_PLACEHOLDER"
TOTAL_STAGES=$(count_pending "${TRACKED_PLACEHOLDERS[@]}")

banner "Stripe setup"

if placeholder_exists "$API_KEY_PLACEHOLDER"; then
  stage "Stripe API key"
  open_url "https://dashboard.stripe.com/test/apikeys"
  step "Copy the test secret key."
  collect_secret "$API_KEY_PLACEHOLDER" "Paste the secret key, or enter :later:"
fi

if placeholder_exists "$OAUTH_PLACEHOLDER"; then
  stage "GitHub OAuth"
  step "Approve the requested integration in the authenticated browser."
  complete_action "$OAUTH_PLACEHOLDER" "已完成"
fi

finish
