#!/usr/bin/env bash
#
# Collect missing sensitive operations input into a private Markdown document.
# Generated by the sensitive-ops skill.
#
# Keep the library above the "STAGES" marker unchanged. Author the missing
# outcomes below it with the exact placeholders already present in the document.

set -euo pipefail
umask 077

OPS_FILE="${SENSITIVE_OPS_FILE:-${HOME}/Documents/LLM/sensitive-ops.md}"
TOTAL_STAGES=0
_STAGE_INDEX=0
TRACKED_PLACEHOLDERS=()
TRACKED_COMPLETION_MARKERS=()
WORKFLOW_TITLE=""
WORKFLOW_MARKER=""
_ACTIVE_TMP=""

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""
fi

_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1 && tput clear 2>/dev/null; then return 0; fi
  printf '\033[2J\033[3J\033[H'
}

say()  { printf '  %s\n' "$1"; }
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

fail() {
  warn "$1"
  exit 1
}

defer() {
  printf '\n  %sProgress saved.%s Run this helper again when you are ready.\n\n' "$YELLOW" "$RESET"
  exit 2
}

cleanup() {
  local status=$?
  if [[ -n "$_ACTIVE_TMP" && -e "$_ACTIVE_TMP" ]]; then rm -f -- "$_ACTIVE_TMP"; fi
  return "$status"
}

trap cleanup EXIT
trap defer INT TERM

configure_workflow() {
  local index marker_prefix='<!-- sensitive-ops:' marker_suffix=' -->' workflow_id
  WORKFLOW_TITLE="$1"
  WORKFLOW_MARKER="$2"
  shift 2
  TRACKED_PLACEHOLDERS=("$@")
  [[ "$WORKFLOW_MARKER" == "$marker_prefix"*"$marker_suffix" ]] || fail "workflow marker must match <!-- sensitive-ops:workflow-id -->"
  workflow_id=${WORKFLOW_MARKER#"$marker_prefix"}
  workflow_id=${workflow_id%"$marker_suffix"}
  [[ "$workflow_id" =~ ^[a-z0-9][a-z0-9-]*$ ]] || fail "workflow id must contain only lowercase letters, digits, and hyphens"
  TRACKED_COMPLETION_MARKERS=()
  for (( index=0; index<${#TRACKED_PLACEHOLDERS[@]}; index++ )); do
    TRACKED_COMPLETION_MARKERS+=("<!-- sensitive-ops:${workflow_id}:outcome-$((index + 1)):complete -->")
  done
}

document_mode() {
  local mode
  if mode=$(stat -f '%Lp' "$OPS_FILE" 2>/dev/null) && [[ "$mode" =~ ^[0-7]{3,4}$ ]]; then
    printf '%s' "$mode"
    return 0
  fi
  if mode=$(stat -c '%a' -- "$OPS_FILE" 2>/dev/null) && [[ "$mode" =~ ^[0-7]{3,4}$ ]]; then
    printf '%s' "$mode"
    return 0
  fi
  return 1
}

validate_document_safety() {
  local mode ops_dir repo_root
  [[ "$OPS_FILE" == /* ]] || fail "operations document path must be absolute: $OPS_FILE"
  [[ ! -L "$OPS_FILE" ]] || fail "operations document must not be a symbolic link: $OPS_FILE"
  [[ -O "$OPS_FILE" ]] || fail "operations document must be owned by the current user: $OPS_FILE"
  mode=$(document_mode) || fail "could not determine operations document permissions: $OPS_FILE"
  (( (8#$mode & 077) == 0 )) || fail "operations document must not grant group or other permissions: $OPS_FILE"
  command -v git >/dev/null 2>&1 || fail "git is required to verify that the operations document is untracked"
  ops_dir=${OPS_FILE%/*}
  [[ -n "$ops_dir" ]] || ops_dir=/
  if repo_root=$(git -C "$ops_dir" rev-parse --show-toplevel 2>/dev/null); then
    if git -C "$repo_root" ls-files --error-unmatch -- "$OPS_FILE" >/dev/null 2>&1; then
      fail "operations document must not be tracked by Git: $OPS_FILE"
    fi
  fi
}

prepare_workflow() {
  local occurrences
  [[ -n "$WORKFLOW_TITLE" ]] || fail "helper has not been authored: workflow title is missing"
  [[ -n "$WORKFLOW_MARKER" ]] || fail "helper has not been authored: workflow marker is missing"
  (( ${#TRACKED_PLACEHOLDERS[@]} > 0 )) || fail "helper has not been authored: no outcomes are registered"
  [[ -f "$OPS_FILE" ]] || fail "operations document does not exist: $OPS_FILE"
  [[ -r "$OPS_FILE" && -w "$OPS_FILE" ]] || fail "operations document is not readable and writable: $OPS_FILE"
  validate_document_safety
  occurrences=$(occurrence_count "$WORKFLOW_MARKER")
  [[ "$occurrences" -eq 1 ]] || fail "expected one workflow marker in $OPS_FILE, found $occurrences"
  validate_outcomes
  TOTAL_STAGES=$(count_pending "${TRACKED_PLACEHOLDERS[@]}")
}

validate_outcomes() {
  local completion completion_occurrences index occurrences placeholder previous registered
  for (( index=0; index<${#TRACKED_PLACEHOLDERS[@]}; index++ )); do
    placeholder=${TRACKED_PLACEHOLDERS[$index]}
    completion=${TRACKED_COMPLETION_MARKERS[$index]}
    [[ -n "$placeholder" ]] || fail "helper has not been authored: an outcome placeholder is empty"
    for (( previous=0; previous<index; previous++ )); do
      registered=${TRACKED_PLACEHOLDERS[$previous]}
      [[ "$registered" != "$placeholder" ]] || fail "an outcome placeholder was registered more than once"
    done
    occurrences=$(occurrence_count "$placeholder")
    completion_occurrences=$(occurrence_count "$completion")
    [[ "$occurrences" -le 1 ]] || fail "expected at most one occurrence of placeholder, found $occurrences"
    [[ "$completion_occurrences" -le 1 ]] || fail "expected at most one occurrence of completion marker, found $completion_occurrences"
    [[ $((occurrences + completion_occurrences)) -eq 1 ]] || fail "outcome $((index + 1)) must contain exactly one placeholder or completion marker"
  done
}

occurrence_count() {
  local needle="$1" line rest count=0
  [[ -n "$needle" ]] || { printf '0'; return; }
  while IFS= read -r line || [[ -n "$line" ]]; do
    rest="$line"
    while [[ "$rest" == *"$needle"* ]]; do
      rest=${rest#*"$needle"}
      count=$((count + 1))
    done
  done < "$OPS_FILE"
  printf '%s' "$count"
}

placeholder_exists() {
  [[ "$(occurrence_count "$1")" -gt 0 ]]
}

count_pending() {
  local placeholder count=0
  for placeholder in "$@"; do
    if placeholder_exists "$placeholder"; then count=$((count + 1)); fi
  done
  printf '%s' "$count"
}

completion_marker_for() {
  local index placeholder="$1"
  for (( index=0; index<${#TRACKED_PLACEHOLDERS[@]}; index++ )); do
    if [[ "${TRACKED_PLACEHOLDERS[$index]}" == "$placeholder" ]]; then
      printf '%s' "${TRACKED_COMPLETION_MARKERS[$index]}"
      return 0
    fi
  done
  return 1
}

banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s remaining stage(s)%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  Durable results are saved to %s.\n' "$DIM" "$OPS_FILE"
  printf '  Enter :later or press Ctrl-C to stop; completed stages are retained.%s\n\n' "$RESET"
}

stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  if command -v wslview >/dev/null 2>&1; then
    wslview "$url" >/dev/null 2>&1 || warn "couldn't open a browser; visit it manually: $url"
  elif command -v explorer.exe >/dev/null 2>&1; then
    explorer.exe "$url" >/dev/null 2>&1 || warn "couldn't open a browser; visit it manually: $url"
  elif command -v xdg-open >/dev/null 2>&1; then
    xdg-open "$url" >/dev/null 2>&1 || warn "couldn't open a browser; visit it manually: $url"
  elif command -v open >/dev/null 2>&1; then
    open "$url" >/dev/null 2>&1 || warn "couldn't open a browser; visit it manually: $url"
  else
    warn "couldn't open a browser; visit it manually: $url"
  fi
}

confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || defer
  [[ "$reply" == ":later" ]] && defer
  [[ "$reply" =~ ^[Yy]$ ]]
}

# Replace an exact placeholder without exposing its value to a child process.
replace_placeholder() {
  local placeholder="$1" value="$2" completion tmp line prefix suffix found=0 occurrences
  validate_document_safety
  completion=$(completion_marker_for "$placeholder") || fail "placeholder is not registered for this workflow"
  occurrences=$(occurrence_count "$placeholder")
  [[ "$occurrences" -eq 1 ]] || fail "expected one occurrence of placeholder, found $occurrences"
  tmp=$(mktemp "${OPS_FILE}.tmp.XXXXXX")
  _ACTIVE_TMP="$tmp"
  cp -p "$OPS_FILE" "$tmp"
  : > "$tmp"
  while IFS= read -r line || [[ -n "$line" ]]; do
    if [[ "$line" == *"$placeholder"* ]]; then
      prefix=${line%%"$placeholder"*}
      suffix=${line#*"$placeholder"}
      line="${prefix}${value}${completion}${suffix}"
      found=$((found + 1))
    fi
    printf '%s\n' "$line" >> "$tmp"
  done < "$OPS_FILE"
  if [[ "$found" -ne 1 ]]; then
    rm -f "$tmp"
    _ACTIVE_TMP=""
    warn "expected one occurrence of placeholder, found $found"
    return 1
  fi
  mv "$tmp" "$OPS_FILE"
  _ACTIVE_TMP=""
}

collect_value() {
  local placeholder="$1" prompt="$2" value=""
  placeholder_exists "$placeholder" || return 0
  while [[ -z "$value" ]]; do
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
    read -r value || defer
    [[ "$value" == ":later" ]] && defer
    [[ -n "$value" ]] || warn "a value is required, or enter :later"
  done
  replace_placeholder "$placeholder" "$value"
  printf '  %s✓ saved%s\n' "$GREEN" "$RESET"
}

collect_secret() {
  local placeholder="$1" prompt="$2" value=""
  placeholder_exists "$placeholder" || return 0
  while [[ -z "$value" ]]; do
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
    read -rs value || defer
    printf '\n'
    [[ "$value" == ":later" ]] && defer
    [[ -n "$value" ]] || warn "a value is required, or enter :later"
  done
  replace_placeholder "$placeholder" "$value"
  value=""
  printf '  %s✓ saved%s\n' "$GREEN" "$RESET"
}

complete_action() {
  local placeholder="$1" result="${2:-已完成}" today
  placeholder_exists "$placeholder" || return 0
  if ! confirm "Have you completed this action?"; then defer; fi
  today=$(date '+%Y-%m-%d')
  replace_placeholder "$placeholder" "${result}（${today}）"
  printf '  %s✓ recorded%s\n' "$GREEN" "$RESET"
}

finish() {
  local remaining
  validate_outcomes
  remaining=$(count_pending "${TRACKED_PLACEHOLDERS[@]}")
  _clear
  if [[ "$remaining" -gt 0 ]]; then
    warn "$remaining tracked outcome(s) remain in $OPS_FILE"
    defer
  fi
  printf '\n%s%s  ✓ Sensitive operations input complete%s\n' "$BOLD" "$GREEN" "$RESET"
  note "The agent can now resume from $OPS_FILE."
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: replace this scaffold with the current task's missing outcomes.
# The shipped template fails closed until this section is replaced.
# ──────────────────────────────────────────────────────────────────────────

# VALUE_PLACEHOLDER='<待填写：具体值>'
# configure_workflow "Setup title" "<!-- sensitive-ops:workflow-id -->" "$VALUE_PLACEHOLDER"
# prepare_workflow
# banner "$WORKFLOW_TITLE"
# if placeholder_exists "$VALUE_PLACEHOLDER"; then
#   stage "Collect value"
#   collect_secret "$VALUE_PLACEHOLDER" "Enter the value, or enter :later:"
# fi
# finish

fail "helper has not been authored: replace the STAGES section"
